"""add a gist index for path of comments

Revision ID: 2f2b054c0a54
Revises: f1582a84a783
Create Date: 2023-09-22 17:37:23.832148

"""
from collections.abc import Sequence

import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f2b054c0a54"
down_revision: str | None = "f1582a84a783"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "comments",
        "path",
        existing_type=sqlalchemy_utils.types.ltree.LtreeType(),
        nullable=False,
    )
    op.create_index(
        "path_gist_idx",
        "comments",
        ["path"],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("path_gist_idx", table_name="comments", postgresql_using="gist")
    op.alter_column(
        "comments",
        "path",
        existing_type=sqlalchemy_utils.types.ltree.LtreeType(),
        nullable=True,
    )
    # ### end Alembic commands ###
