"""make posts.user_id nullable

Revision ID: 32b321ea6ac7
Revises: f9113e99878b
Create Date: 2023-09-08 21:08:57.413429

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32b321ea6ac7"
down_revision: str | None = "f9113e99878b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "posts",
        "user_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "posts",
        "user_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    # ### end Alembic commands ###
