"""revert back the nullability of path on comments table

Revision ID: a557eeda29b1
Revises: 2f2b054c0a54
Create Date: 2023-09-22 17:47:11.554206

"""
from collections.abc import Sequence

import sqlalchemy_utils
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a557eeda29b1"
down_revision: str | None = "2f2b054c0a54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "comments",
        "path",
        existing_type=sqlalchemy_utils.types.ltree.LtreeType(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "comments",
        "path",
        existing_type=sqlalchemy_utils.types.ltree.LtreeType(),
        nullable=False,
    )
    # ### end Alembic commands ###
