"""add updated columns to PostModel, UserModel and DraftModel

Revision ID: a90cc0025977
Revises: 6e4a0b3ff89b
Create Date: 2023-10-10 21:46:10.478301

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a90cc0025977"
down_revision: str | None = "6e4a0b3ff89b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("drafts", sa.Column("updated", sa.DateTime(), nullable=True))
    op.add_column("posts", sa.Column("updated", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("updated", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated")
    op.drop_column("posts", "updated")
    op.drop_column("drafts", "updated")
    # ### end Alembic commands ###
