"""Add updated to CommentModel

Revision ID: aa0f5ca3f1d4
Revises: 7ca65d8bfa74
Create Date: 2023-10-11 10:05:50.103938

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa0f5ca3f1d4"
down_revision: str | None = "7ca65d8bfa74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("updated", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comments", "updated")
    # ### end Alembic commands ###
