"""add url column to PostModel

Revision ID: b216f1e9cb11
Revises: b48c2269c53d
Create Date: 2023-09-12 10:55:35.499602

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b216f1e9cb11"
down_revision: str | None = "b48c2269c53d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("url", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "url")
    # ### end Alembic commands ###
