"""add username fk to CommentModel

Revision ID: b7b67548bec8
Revises: a557eeda29b1
Create Date: 2023-09-27 09:12:41.408990

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b7b67548bec8"
down_revision: str | None = "a557eeda29b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("username", sa.String(), nullable=False))
    op.create_foreign_key(None, "comments", "users", ["username"], ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_column("comments", "username")
    # ### end Alembic commands ###
