"""Add UserModel

Revision ID: bdd5e9a5b364
Revises: 9f16587d7cc1
Create Date: 2023-09-08 18:05:44.624540

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bdd5e9a5b364"
down_revision: str | None = "9f16587d7cc1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("posts", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(None, "posts", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_column("posts", "user_id")
    op.drop_table("users")
    # ### end Alembic commands ###
