"""Add created column to users table

Revision ID: d504614ad8a1
Revises: 5d30fcc241a3
Create Date: 2023-09-11 14:47:22.669966

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d504614ad8a1"
down_revision: str | None = "5d30fcc241a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("created", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created")
    # ### end Alembic commands ###
