"""save comment paths in comment model

Revision ID: f1582a84a783
Revises: f75bf4f86710
Create Date: 2023-09-22 15:10:57.106886

"""
from collections.abc import Sequence

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f1582a84a783"
down_revision: str | None = "f75bf4f86710"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comments",
        sa.Column("path", sqlalchemy_utils.types.ltree.LtreeType(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comments", "path")
    # ### end Alembic commands ###
