"""make the rel between post and its comments bidirectional

Revision ID: f75bf4f86710
Revises: 02ad2b0cb214
Create Date: 2023-09-22 13:02:33.838341

"""
from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "f75bf4f86710"
down_revision: str | None = "02ad2b0cb214"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
