name: testing the app
run-name: Test the app
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - main

env:
  DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432
  SECRET_KEY: laskdjflaskdjfosdf98suidfjjksdf98sduf


jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Setup PostgreSQL with PostgreSQL extensions and unprivileged user
        uses: Daniel-Marynicz/postgresql-action@1.0.0

      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --no-ansi --no-interaction --with test --without dev

      - name: Test
        run: poetry run pytest --cov=src -v
